ServerEvents.recipes((event) => {
    event.remove({ type: "mysticalagriculture:soul_extraction" });
    event.remove({ type: "mysticalagriculture:reprocessor" });

    //// # =================================================================================================== #

    //#region Remove ID
    const RmRecipeID = [
        //Mystical Seed
        ////Crafting
        //T0
        "mysticalagriculture:seed/crafting/air",
        "mysticalagriculture:seed/crafting/earth",
        "mysticalagriculture:seed/crafting/water",
        "mysticalagriculture:seed/crafting/fire",

        //T1
        "mysticalagriculture:seed/crafting/inferium",
        "mysticalagriculture:seed/crafting/stone",
        "mysticalagriculture:seed/crafting/dirt",
        "mysticalagriculture:seed/crafting/wood",
        "mysticalagriculture:seed/crafting/ice",
        "mysticalagriculture:seed/crafting/deepslate",

        //T2
        "mysticalagriculture:seed/crafting/nature",
        "mysticalagriculture:seed/crafting/dye",
        "mysticalagriculture:seed/crafting/nether",
        "mysticalagriculture:seed/crafting/coal",
        "mysticalagriculture:seed/crafting/coral",
        "mysticalagriculture:seed/crafting/honey",
        "mysticalagriculture:seed/crafting/amethyst",
        "mysticalagriculture:seed/crafting/pig",
        "mysticalagriculture:seed/crafting/chicken",
        "mysticalagriculture:seed/crafting/cow",
        "mysticalagriculture:seed/crafting/sheep",
        "mysticalagriculture:seed/crafting/squid",
        "mysticalagriculture:seed/crafting/fish",
        "mysticalagriculture:seed/crafting/slime",
        "mysticalagriculture:seed/crafting/turtle",
        "mysticalagriculture:seed/crafting/rubber",
        "mysticalagriculture:seed/crafting/silicon",
        "mysticalagriculture:seed/crafting/sulfur",
        "mysticalagriculture:seed/crafting/aluminum",
        "mysticalagriculture:seed/crafting/saltpeter",
        "mysticalagriculture:seed/crafting/apatite",
        "mysticalagriculture:seed/crafting/grains_of_infinity",
        "mysticalagriculture:seed/crafting/mystical_flower",
        "mysticalagriculture:seed/crafting/marble",
        "mysticalagriculture:seed/crafting/limestone",
        "mysticalagriculture:seed/crafting/basalt",

        //T3
        "mysticalagriculture:seed/crafting/iron",
        "mysticalagriculture:seed/crafting/copper",
        "mysticalagriculture:seed/crafting/nether_quartz",
        "mysticalagriculture:seed/crafting/glowstone",
        "mysticalagriculture:seed/crafting/redstone",
        "mysticalagriculture:seed/crafting/obsidian",
        "mysticalagriculture:seed/crafting/prismarine",
        "mysticalagriculture:seed/crafting/zombie",
        "mysticalagriculture:seed/crafting/skeleton",
        "mysticalagriculture:seed/crafting/creeper",
        "mysticalagriculture:seed/crafting/spider",
        "mysticalagriculture:seed/crafting/rabbit",
        "mysticalagriculture:seed/crafting/tin",
        "mysticalagriculture:seed/crafting/bronze",
        "mysticalagriculture:seed/crafting/zinc",
        "mysticalagriculture:seed/crafting/brass",
        "mysticalagriculture:seed/crafting/silver",
        "mysticalagriculture:seed/crafting/lead",
        "mysticalagriculture:seed/crafting/graphite",
        "mysticalagriculture:seed/crafting/blizz",
        "mysticalagriculture:seed/crafting/blitz",
        "mysticalagriculture:seed/crafting/basalz",
        "mysticalagriculture:seed/crafting/copper_alloy",
        "mysticalagriculture:seed/crafting/redstone_alloy",
        "mysticalagriculture:seed/crafting/conductive_alloy",
        "mysticalagriculture:seed/crafting/manasteel",
        "mysticalagriculture:seed/crafting/steeleaf",
        "mysticalagriculture:seed/crafting/ironwood",
        "mysticalagriculture:seed/crafting/sky_stone",
        "mysticalagriculture:seed/crafting/certus_quartz",

        //T4
        "mysticalagriculture:seed/crafting/gold",
        "mysticalagriculture:seed/crafting/lapis_lazuli",
        "mysticalagriculture:seed/crafting/end",
        "mysticalagriculture:seed/crafting/experience",
        "mysticalagriculture:seed/crafting/blaze",
        "mysticalagriculture:seed/crafting/ghast",
        "mysticalagriculture:seed/crafting/enderman",
        "mysticalagriculture:seed/crafting/steel",
        "mysticalagriculture:seed/crafting/nickel",
        "mysticalagriculture:seed/crafting/constantan",
        "mysticalagriculture:seed/crafting/electrum",
        "mysticalagriculture:seed/crafting/invar",
        "mysticalagriculture:seed/crafting/mithril",
        "mysticalagriculture:seed/crafting/tungsten",
        "mysticalagriculture:seed/crafting/titanium",
        "mysticalagriculture:seed/crafting/uranium",
        "mysticalagriculture:seed/crafting/chrome",
        "mysticalagriculture:seed/crafting/ruby",
        "mysticalagriculture:seed/crafting/sapphire",
        "mysticalagriculture:seed/crafting/peridot",
        "mysticalagriculture:seed/crafting/soulium",
        "mysticalagriculture:seed/crafting/signalum",
        "mysticalagriculture:seed/crafting/lumium",
        "mysticalagriculture:seed/crafting/flux_infused_ingot",
        "mysticalagriculture:seed/crafting/hop_graphite",
        "mysticalagriculture:seed/crafting/soularium",
        "mysticalagriculture:seed/crafting/dark_steel",
        "mysticalagriculture:seed/crafting/pulsating_alloy",
        "mysticalagriculture:seed/crafting/energetic_alloy",
        "mysticalagriculture:seed/crafting/elementium",
        "mysticalagriculture:seed/crafting/osmium",
        "mysticalagriculture:seed/crafting/fluorite",
        "mysticalagriculture:seed/crafting/refined_glowstone",
        "mysticalagriculture:seed/crafting/refined_obsidian",
        "mysticalagriculture:seed/crafting/knightmetal",
        "mysticalagriculture:seed/crafting/fiery_ingot",
        "mysticalagriculture:seed/crafting/compressed_iron",
        "mysticalagriculture:seed/crafting/fluix",
        "mysticalagriculture:seed/crafting/energized_steel",
        "mysticalagriculture:seed/crafting/blazing_crystal",

        //T5
        "mysticalagriculture:seed/crafting/diamond",
        "mysticalagriculture:seed/crafting/emerald",
        "mysticalagriculture:seed/crafting/netherite",
        "mysticalagriculture:seed/crafting/wither_skeleton",
        "mysticalagriculture:seed/crafting/platinum",
        "mysticalagriculture:seed/crafting/iridium",
        "mysticalagriculture:seed/crafting/enderium",
        "mysticalagriculture:seed/crafting/flux_infused_gem",
        "mysticalagriculture:seed/crafting/vibrant_alloy",
        "mysticalagriculture:seed/crafting/end_steel",
        "mysticalagriculture:seed/crafting/terrasteel",
        "mysticalagriculture:seed/crafting/yellorium",
        "mysticalagriculture:seed/crafting/cyanite",
        "mysticalagriculture:seed/crafting/niotic_crystal",
        "mysticalagriculture:seed/crafting/spirited_crystal",
        "mysticalagriculture:seed/crafting/uraninite",

        //T6
        "mysticalagriculture:seed/crafting/nether_star",
        "mysticalagriculture:seed/crafting/dragon_egg",
        "mysticalagriculture:seed/crafting/gaia_spirit",
        "mysticalagriculture:seed/crafting/neutronium",
        "mysticalagriculture:seed/crafting/nitro_crystal",

        ////Infusion
        //T0
        "mysticalagriculture:seed/infusion/air",
        "mysticalagriculture:seed/infusion/earth",
        "mysticalagriculture:seed/infusion/water",
        "mysticalagriculture:seed/infusion/fire",

        //T1
        "mysticalagriculture:seed/infusion/inferium",
        "mysticalagriculture:seed/infusion/stone",
        "mysticalagriculture:seed/infusion/dirt",
        "mysticalagriculture:seed/infusion/wood",
        "mysticalagriculture:seed/infusion/ice",
        "mysticalagriculture:seed/infusion/deepslate",

        //T2
        "mysticalagriculture:seed/infusion/nature",
        "mysticalagriculture:seed/infusion/dye",
        "mysticalagriculture:seed/infusion/nether",
        "mysticalagriculture:seed/infusion/coal",
        "mysticalagriculture:seed/infusion/coral",
        "mysticalagriculture:seed/infusion/honey",
        "mysticalagriculture:seed/infusion/amethyst",
        "mysticalagriculture:seed/infusion/pig",
        "mysticalagriculture:seed/infusion/chicken",
        "mysticalagriculture:seed/infusion/cow",
        "mysticalagriculture:seed/infusion/sheep",
        "mysticalagriculture:seed/infusion/squid",
        "mysticalagriculture:seed/infusion/fish",
        "mysticalagriculture:seed/infusion/slime",
        "mysticalagriculture:seed/infusion/turtle",
        "mysticalagriculture:seed/infusion/rubber",
        "mysticalagriculture:seed/infusion/silicon",
        "mysticalagriculture:seed/infusion/sulfur",
        "mysticalagriculture:seed/infusion/aluminum",
        "mysticalagriculture:seed/infusion/saltpeter",
        "mysticalagriculture:seed/infusion/apatite",
        "mysticalagriculture:seed/infusion/grains_of_infinity",
        "mysticalagriculture:seed/infusion/mystical_flower",
        "mysticalagriculture:seed/infusion/marble",
        "mysticalagriculture:seed/infusion/limestone",
        "mysticalagriculture:seed/infusion/basalt",

        //T3
        "mysticalagriculture:seed/infusion/iron",
        "mysticalagriculture:seed/infusion/copper",
        "mysticalagriculture:seed/infusion/nether_quartz",
        "mysticalagriculture:seed/infusion/glowstone",
        "mysticalagriculture:seed/infusion/redstone",
        "mysticalagriculture:seed/infusion/obsidian",
        "mysticalagriculture:seed/infusion/prismarine",
        "mysticalagriculture:seed/infusion/zombie",
        "mysticalagriculture:seed/infusion/skeleton",
        "mysticalagriculture:seed/infusion/creeper",
        "mysticalagriculture:seed/infusion/spider",
        "mysticalagriculture:seed/infusion/rabbit",
        "mysticalagriculture:seed/infusion/tin",
        "mysticalagriculture:seed/infusion/bronze",
        "mysticalagriculture:seed/infusion/zinc",
        "mysticalagriculture:seed/infusion/brass",
        "mysticalagriculture:seed/infusion/silver",
        "mysticalagriculture:seed/infusion/lead",
        "mysticalagriculture:seed/infusion/graphite",
        "mysticalagriculture:seed/infusion/blizz",
        "mysticalagriculture:seed/infusion/blitz",
        "mysticalagriculture:seed/infusion/basalz",
        "mysticalagriculture:seed/infusion/copper_alloy",
        "mysticalagriculture:seed/infusion/redstone_alloy",
        "mysticalagriculture:seed/infusion/conductive_alloy",
        "mysticalagriculture:seed/infusion/manasteel",
        "mysticalagriculture:seed/infusion/steeleaf",
        "mysticalagriculture:seed/infusion/ironwood",
        "mysticalagriculture:seed/infusion/sky_stone",
        "mysticalagriculture:seed/infusion/certus_quartz",

        //T4
        "mysticalagriculture:seed/infusion/gold",
        "mysticalagriculture:seed/infusion/lapis_lazuli",
        "mysticalagriculture:seed/infusion/end",
        "mysticalagriculture:seed/infusion/experience",
        "mysticalagriculture:seed/infusion/blaze",
        "mysticalagriculture:seed/infusion/ghast",
        "mysticalagriculture:seed/infusion/enderman",
        "mysticalagriculture:seed/infusion/steel",
        "mysticalagriculture:seed/infusion/nickel",
        "mysticalagriculture:seed/infusion/constantan",
        "mysticalagriculture:seed/infusion/electrum",
        "mysticalagriculture:seed/infusion/invar",
        "mysticalagriculture:seed/infusion/mithril",
        "mysticalagriculture:seed/infusion/tungsten",
        "mysticalagriculture:seed/infusion/titanium",
        "mysticalagriculture:seed/infusion/uranium",
        "mysticalagriculture:seed/infusion/chrome",
        "mysticalagriculture:seed/infusion/ruby",
        "mysticalagriculture:seed/infusion/sapphire",
        "mysticalagriculture:seed/infusion/peridot",
        "mysticalagriculture:seed/infusion/soulium",
        "mysticalagriculture:seed/infusion/signalum",
        "mysticalagriculture:seed/infusion/lumium",
        "mysticalagriculture:seed/infusion/flux_infused_ingot",
        "mysticalagriculture:seed/infusion/hop_graphite",
        "mysticalagriculture:seed/infusion/soularium",
        "mysticalagriculture:seed/infusion/dark_steel",
        "mysticalagriculture:seed/infusion/pulsating_alloy",
        "mysticalagriculture:seed/infusion/energetic_alloy",
        "mysticalagriculture:seed/infusion/elementium",
        "mysticalagriculture:seed/infusion/osmium",
        "mysticalagriculture:seed/infusion/fluorite",
        "mysticalagriculture:seed/infusion/refined_glowstone",
        "mysticalagriculture:seed/infusion/refined_obsidian",
        "mysticalagriculture:seed/infusion/knightmetal",
        "mysticalagriculture:seed/infusion/fiery_ingot",
        "mysticalagriculture:seed/infusion/compressed_iron",
        "mysticalagriculture:seed/infusion/fluix",
        "mysticalagriculture:seed/infusion/energized_steel",
        "mysticalagriculture:seed/infusion/blazing_crystal",

        //T5
        "mysticalagriculture:seed/infusion/diamond",
        "mysticalagriculture:seed/infusion/emerald",
        "mysticalagriculture:seed/infusion/netherite",
        "mysticalagriculture:seed/infusion/wither_skeleton",
        "mysticalagriculture:seed/infusion/platinum",
        "mysticalagriculture:seed/infusion/iridium",
        "mysticalagriculture:seed/infusion/enderium",
        "mysticalagriculture:seed/infusion/flux_infused_gem",
        "mysticalagriculture:seed/infusion/vibrant_alloy",
        "mysticalagriculture:seed/infusion/end_steel",
        "mysticalagriculture:seed/infusion/terrasteel",
        "mysticalagriculture:seed/infusion/yellorium",
        "mysticalagriculture:seed/infusion/cyanite",
        "mysticalagriculture:seed/infusion/niotic_crystal",
        "mysticalagriculture:seed/infusion/spirited_crystal",
        "mysticalagriculture:seed/infusion/uraninite",

        //T6
        "mysticalagriculture:seed/infusion/nether_star",
        "mysticalagriculture:seed/infusion/dragon_egg",
        "mysticalagriculture:seed/infusion/gaia_spirit",
        "mysticalagriculture:seed/infusion/neutronium",
        "mysticalagriculture:seed/infusion/nitro_crystal",
    ];
    RmRecipeID.forEach((id) => event.remove({ id: id }));
    //#endregion

    //// # =================================================================================================== #

    //Altar
    event.remove({ output: "mysticalagriculture:infusion_altar" });
    event.shaped("mysticalagriculture:infusion_altar", ["ABA", " C ", "DDD"], { A: "#forge:ingots/gold", B: "minecraft:red_carpet", C: "rootsclassic:altar", D: "minecraft:stone" });

    //Pedastal
    event.remove({ output: "mysticalagriculture:infusion_pedestal" });
    event.shaped("mysticalagriculture:infusion_pedestal", ["ABA", " C ", " D "], { A: "#forge:ingots/gold", B: "minecraft:red_carpet", C: "rootsclassic:attuned_standing_stone", D: "minecraft:stone" });

    //Awaken altar
    event.remove({ output: "mysticalagriculture:awakening_altar" });
    event.shaped("mysticalagriculture:awakening_altar", ["ABA", " C ", "DDD"], { A: "#forge:ingots/gold", B: "minecraft:orange_carpet", C: "mysticalagriculture:infusion_altar", D: "mysticalagriculture:soulstone" });

    //Awaken Pedastal
    event.remove({ output: "mysticalagriculture:awakening_pedestal" });
    event.shaped("mysticalagriculture:awakening_pedestal", ["ABA", " C ", " D "], { A: "#forge:ingots/gold", B: "minecraft:orange_carpet", C: "mysticalagriculture:infusion_pedestal", D: "mysticalagriculture:soulstone" });

    //Awaken Vessel
    event.remove({ output: "mysticalagriculture:essence_vessel" });
    event.shaped("mysticalagriculture:essence_vessel", ["ABA", " C ", " D "], { A: "#forge:ingots/gold", B: "supplementaries:jar", C: "mysticalagriculture:infusion_pedestal", D: "mysticalagriculture:soulstone" });

    //// # =================================================================================================== #

    //#region Reprocessor
    const ReprocessorPattern = [
        //T0
        { get: "mysticalagriculture:air_essence", put: "mysticalagriculture:air_seeds" },
        { get: "mysticalagriculture:earth_essence", put: "mysticalagriculture:earth_seeds" },
        { get: "mysticalagriculture:water_essence", put: "mysticalagriculture:water_seeds" },
        { get: "mysticalagriculture:fire_essence", put: "mysticalagriculture:fire_seeds" },

        //T1
        { get: "mysticalagriculture:inferium_essence", put: "mysticalagriculture:inferium_seeds" },
        { get: "mysticalagriculture:stone_essence", put: "mysticalagriculture:stone_seeds" },
        { get: "mysticalagriculture:dirt_essence", put: "mysticalagriculture:dirt_seeds" },
        { get: "mysticalagriculture:wood_essence", put: "mysticalagriculture:wood_seeds" },
        { get: "mysticalagriculture:ice_essence", put: "mysticalagriculture:ice_seeds" },
        { get: "mysticalagriculture:deepslate_essence", put: "mysticalagriculture:deepslate_seeds" },

        //T2
        { get: "mysticalagriculture:nature_essence", put: "mysticalagriculture:nature_seeds" },
        //{ get: "mysticalagriculture:dye_essence", put: "mysticalagriculture:dye_seeds" },
        { get: "mysticalagriculture:nether_essence", put: "mysticalagriculture:nether_seeds" },
        { get: "mysticalagriculture:coal_essence", put: "mysticalagriculture:coal_seeds" },
        { get: "mysticalagriculture:coral_essence", put: "mysticalagriculture:coral_seeds" },
        { get: "mysticalagriculture:honey_essence", put: "mysticalagriculture:honey_seeds" },
        { get: "mysticalagriculture:amethyst_essence", put: "mysticalagriculture:amethyst_seeds" },
        { get: "mysticalagriculture:pig_essence", put: "mysticalagriculture:pig_seeds" },
        { get: "mysticalagriculture:chicken_essence", put: "mysticalagriculture:chicken_seeds" },
        { get: "mysticalagriculture:cow_essence", put: "mysticalagriculture:cow_seeds" },
        { get: "mysticalagriculture:sheep_essence", put: "mysticalagriculture:sheep_seeds" },
        { get: "mysticalagriculture:squid_essence", put: "mysticalagriculture:squid_seeds" },
        { get: "mysticalagriculture:fish_essence", put: "mysticalagriculture:fish_seeds" },
        { get: "mysticalagriculture:slime_essence", put: "mysticalagriculture:slime_seeds" },
        { get: "mysticalagriculture:turtle_essence", put: "mysticalagriculture:turtle_seeds" },
        //{ get: "mysticalagriculture:rubber_essence", put: "mysticalagriculture:rubber_seeds" },
        //{ get: "mysticalagriculture:silicon_essence", put: "mysticalagriculture:silicon_seeds" },
        { get: "mysticalagriculture:sulfur_essence", put: "mysticalagriculture:sulfur_seeds" },
        { get: "mysticalagriculture:aluminum_essence", put: "mysticalagriculture:aluminum_seeds" },
        { get: "mysticalagriculture:saltpeter_essence", put: "mysticalagriculture:saltpeter_seeds" },
        { get: "mysticalagriculture:apatite_essence", put: "mysticalagriculture:apatite_seeds" },
        //{ get: "mysticalagriculture:grains_of_infinity_essence", put: "mysticalagriculture:grains_of_infinity_seeds" },
        //{ get: "mysticalagriculture:mystical_flower_essence", put: "mysticalagriculture:mystical_flower_seeds" },
        //{ get: "mysticalagriculture:marble_essence", put: "mysticalagriculture:marble_seeds" },
        //{ get: "mysticalagriculture:limestone_essence", put: "mysticalagriculture:limestone_seeds" },
        //{ get: "mysticalagriculture:basalt_essence", put: "mysticalagriculture:basalt_seeds" },

        //T3
        { get: "mysticalagriculture:iron_essence", put: "mysticalagriculture:iron_seeds" },
        { get: "mysticalagriculture:copper_essence", put: "mysticalagriculture:copper_seeds" },
        { get: "mysticalagriculture:nether_quartz_essence", put: "mysticalagriculture:nether_quartz_seeds" },
        { get: "mysticalagriculture:glowstone_essence", put: "mysticalagriculture:glowstone_seeds" },
        { get: "mysticalagriculture:redstone_essence", put: "mysticalagriculture:redstone_seeds" },
        { get: "mysticalagriculture:obsidian_essence", put: "mysticalagriculture:obsidian_seeds" },
        { get: "mysticalagriculture:prismarine_essence", put: "mysticalagriculture:prismarine_seeds" },
        { get: "mysticalagriculture:zombie_essence", put: "mysticalagriculture:zombie_seeds" },
        { get: "mysticalagriculture:skeleton_essence", put: "mysticalagriculture:skeleton_seeds" },
        { get: "mysticalagriculture:creeper_essence", put: "mysticalagriculture:creeper_seeds" },
        { get: "mysticalagriculture:spider_essence", put: "mysticalagriculture:spider_seeds" },
        { get: "mysticalagriculture:rabbit_essence", put: "mysticalagriculture:rabbit_seeds" },
        { get: "mysticalagriculture:tin_essence", put: "mysticalagriculture:tin_seeds" },
        //{ get: "mysticalagriculture:bronze_essence", put: "mysticalagriculture:bronze_seeds" },
        { get: "mysticalagriculture:zinc_essence", put: "mysticalagriculture:zinc_seeds" },
        //{ get: "mysticalagriculture:brass_essence", put: "mysticalagriculture:brass_seeds" },
        { get: "mysticalagriculture:silver_essence", put: "mysticalagriculture:silver_seeds" },
        { get: "mysticalagriculture:lead_essence", put: "mysticalagriculture:lead_seeds" },
        //{ get: "mysticalagriculture:graphite_essence", put: "mysticalagriculture:graphite_seeds" },
        { get: "mysticalagriculture:blizz_essence", put: "mysticalagriculture:blizz_seeds" },
        { get: "mysticalagriculture:blitz_essence", put: "mysticalagriculture:blitz_seeds" },
        { get: "mysticalagriculture:basalz_essence", put: "mysticalagriculture:basalz_seeds" },
        //{ get: "mysticalagriculture:copper_alloy_essence", put: "mysticalagriculture:copper_alloy_seeds" },
        //{ get: "mysticalagriculture:redstone_alloy_essence", put: "mysticalagriculture:redstone_alloy_seeds" },
        //{ get: "mysticalagriculture:conductive_alloy_essence", put: "mysticalagriculture:conductive_alloy_seeds" },
        //{ get: "mysticalagriculture:manasteel_essence", put: "mysticalagriculture:manasteel_seeds" },
        { get: "mysticalagriculture:steeleaf_essence", put: "mysticalagriculture:steeleaf_seeds" },
        //{ get: "mysticalagriculture:ironwood_essence", put: "mysticalagriculture:ironwood_seeds" },
        { get: "mysticalagriculture:sky_stone_essence", put: "mysticalagriculture:sky_stone_seeds" },
        { get: "mysticalagriculture:certus_quartz_essence", put: "mysticalagriculture:certus_quartz_seeds" },

        //T4
        { get: "mysticalagriculture:gold_essence", put: "mysticalagriculture:gold_seeds" },
        { get: "mysticalagriculture:lapis_lazuli_essence", put: "mysticalagriculture:lapis_lazuli_seeds" },
        { get: "mysticalagriculture:end_essence", put: "mysticalagriculture:end_seeds" },
        //{ get: "mysticalagriculture:experience_essence", put: "mysticalagriculture:experience_seeds" },
        { get: "mysticalagriculture:blaze_essence", put: "mysticalagriculture:blaze_seeds" },
        { get: "mysticalagriculture:ghast_essence", put: "mysticalagriculture:ghast_seeds" },
        { get: "mysticalagriculture:enderman_essence", put: "mysticalagriculture:enderman_seeds" },
        //{ get: "mysticalagriculture:steel_essence", put: "mysticalagriculture:steel_seeds" },
        { get: "mysticalagriculture:nickel_essence", put: "mysticalagriculture:nickel_seeds" },
        //{ get: "mysticalagriculture:constantan_essence", put: "mysticalagriculture:constantan_seeds" },
        //{ get: "mysticalagriculture:electrum_essence", put: "mysticalagriculture:electrum_seeds" },
        //{ get: "mysticalagriculture:invar_essence", put: "mysticalagriculture:invar_seeds" },
        //{ get: "mysticalagriculture:mithril_essence", put: "mysticalagriculture:mithril_seeds" },
        //{ get: "mysticalagriculture:tungsten_essence", put: "mysticalagriculture:tungsten_seeds" },
        //{ get: "mysticalagriculture:titanium_essence", put: "mysticalagriculture:titanium_seeds" },
        { get: "mysticalagriculture:uranium_essence", put: "mysticalagriculture:uranium_seeds" },
        //{ get: "mysticalagriculture:chrome_essence", put: "mysticalagriculture:chrome_seeds" },
        { get: "mysticalagriculture:ruby_essence", put: "mysticalagriculture:ruby_seeds" },
        { get: "mysticalagriculture:sapphire_essence", put: "mysticalagriculture:sapphire_seeds" },
        { get: "mysticalagriculture:peridot_essence", put: "mysticalagriculture:peridot_seeds" },
        { get: "mysticalagriculture:soulium_essence", put: "mysticalagriculture:soulium_seeds" },
        //{ get: "mysticalagriculture:signalum_essence", put: "mysticalagriculture:signalum_seeds" },
        //{ get: "mysticalagriculture:lumium_essence", put: "mysticalagriculture:lumium_seeds" },
        //{ get: "mysticalagriculture:flux_infused_ingot_essence", put: "mysticalagriculture:flux_infused_ingot_seeds" },
        //{ get: "mysticalagriculture:hop_graphite_essence", put: "mysticalagriculture:hop_graphite_seeds" },
        //{ get: "mysticalagriculture:soularium_essence", put: "mysticalagriculture:soularium_seeds" },
        //{ get: "mysticalagriculture:dark_steel_essence", put: "mysticalagriculture:dark_steel_seeds" },
        //{ get: "mysticalagriculture:pulsating_alloy_essence", put: "mysticalagriculture:pulsating_alloy_seeds" },
        //{ get: "mysticalagriculture:energetic_alloy_essence", put: "mysticalagriculture:energetic_alloy_seeds" },
        //{ get: "mysticalagriculture:elementium_essence", put: "mysticalagriculture:elementium_seeds" },
        { get: "mysticalagriculture:osmium_essence", put: "mysticalagriculture:osmium_seeds" },
        { get: "mysticalagriculture:fluorite_essence", put: "mysticalagriculture:fluorite_seeds" },
        //{ get: "mysticalagriculture:refined_glowstone_essence", put: "mysticalagriculture:refined_glowstone_seeds" },
        //{ get: "mysticalagriculture:refined_obsidian_essence", put: "mysticalagriculture:refined_obsidian_seeds" },
        { get: "mysticalagriculture:knightmetal_essence", put: "mysticalagriculture:knightmetal_seeds" },
        { get: "mysticalagriculture:fiery_ingot_essence", put: "mysticalagriculture:fiery_ingot_seeds" },
        //{ get: "mysticalagriculture:compressed_iron_essence", put: "mysticalagriculture:compressed_iron_seeds" },
        //{ get: "mysticalagriculture:fluix_essence", put: "mysticalagriculture:fluix_seeds" },
        //{ get: "mysticalagriculture:energized_steel_essence", put: "mysticalagriculture:energized_steel_seeds" },
        //{ get: "mysticalagriculture:blazing_crystal_essence", put: "mysticalagriculture:blazing_crystal_seeds" },

        //T5
        { get: "mysticalagriculture:diamond_essence", put: "mysticalagriculture:diamond_seeds" },
        { get: "mysticalagriculture:emerald_essence", put: "mysticalagriculture:emerald_seeds" },
        { get: "mysticalagriculture:netherite_essence", put: "mysticalagriculture:netherite_seeds" },
        { get: "mysticalagriculture:wither_skeleton_essence", put: "mysticalagriculture:wither_skeleton_seeds" },
        { get: "mysticalagriculture:platinum_essence", put: "mysticalagriculture:platinum_seeds" },
        //{ get: "mysticalagriculture:iridium_essence", put: "mysticalagriculture:iridium_seeds" },
        //{ get: "mysticalagriculture:enderium_essence", put: "mysticalagriculture:enderium_seeds" },
        //{ get: "mysticalagriculture:flux_infused_gem_essence", put: "mysticalagriculture:flux_infused_gem_seeds" },
        //{ get: "mysticalagriculture:vibrant_alloy_essence", put: "mysticalagriculture:vibrant_alloy_seeds" },
        //{ get: "mysticalagriculture:end_steel_essence", put: "mysticalagriculture:end_steel_seeds" },
        //{ get: "mysticalagriculture:terrasteel_essence", put: "mysticalagriculture:terrasteel_seeds" },
        //{ get: "mysticalagriculture:yellorium_essence", put: "mysticalagriculture:yellorium_seeds" },
        //{ get: "mysticalagriculture:cyanite_essence", put: "mysticalagriculture:cyanite_seeds" },
        //{ get: "mysticalagriculture:niotic_crystal_essence", put: "mysticalagriculture:niotic_crystal_seeds" },
        //{ get: "mysticalagriculture:spirited_crystal_essence", put: "mysticalagriculture:spirited_crystal_seeds" },
        //{ get: "mysticalagriculture:uraninite_essence", put: "mysticalagriculture:uraninite_seeds" },

        //T6
        { get: "mysticalagriculture:nether_star_essence", put: "mysticalagriculture:nether_star_seeds" },
        { get: "mysticalagriculture:dragon_egg_essence", put: "mysticalagriculture:dragon_egg_seeds" },
        { get: "mysticalagriculture:gaia_spirit_essence", put: "mysticalagriculture:gaia_spirit_seeds" },
        //{ get: "mysticalagriculture:neutronium_essence", put: "mysticalagriculture:neutronium_seeds" },
        //{ get: "mysticalagriculture:nitro_crystal_essence", put: "mysticalagriculture:nitro_crystal_seeds" },
    ];
    ReprocessorPattern.forEach((recipe) => {
        event.custom({
            type: "mysticalagriculture:reprocessor",
            input: { item: recipe.put },
            result: { count: 2, item: recipe.get },
        });
    });
    //#endregion
});
