
["Botany Pots Tiers Options"]
	#
	#Elite Botany Pot Speed
	#Range: > 1
	eliteBotanyPotSpeed = 1
	#
	#Elite Botany Pot Multiplier
	#Range: > 1
	eliteBotanyPotMultiplier = 3
	#
	#Ultra Botany Pot Speed
	#Range: > 1
	ultraBotanyPotSpeed = 1
	#
	#Ultra Botany Pot Multiplier
	#Range: > 1
	ultraBotanyPotMultiplier = 5
	#
	#Creative Botany Pot Speed
	#Range: > 1
	creativeBotanyPotSpeed = 1
	#
	#Creative Botany Pot Multiplier
	#Range: > 1
	creativeBotanyPotMultiplier = 7

